language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- npm run build
- npm run test
- npm run cover
- npm run report
env:
  global:
    secure: 1B/uvzX9pBUUE23uSapxQcL5Ra0omBwbG043R6xhd0rd6AFnVwIJH7KErSnskRMhbmaTMFrAZOAXfh6IAxA2PR0mFNsGZVIYTBXmv3TOY88y7DJlPoByE5m+h78mEF5OiM2ftY+rLhtXekR4QkQTE3Mw4wJcBgcJ5E00C9K9bDqBWpmMrdPa33Tbo4shG40L4oT8PvZIJTRqNkX7BzkkXZZKsX5Yq+BhfLEZnYUTFem0Eg02edPfZcgs4igBY3f+MXXW+1i3t8OgIG90S25E4E2i43kzUBSq/CCCdpNj0agcHm5t67sBXRhlZ6BaWycfCBSui6Uzup2BSNKFG1c+00X0xlvlMXJ3Biy8Pl8gtiICc77+thvh+juAcmrfMVRjEMqbQXJqsKDkzQk+MRiOXYWjHYOa1DSmd89jYJFpzFAM5L6RoxDUC8QP1xLssluGC60ipqSYVwz4DsjN6sl8Kfu4Xk6sZXCBmWmPyNevVBvPOC7BPoN6ANnHE5+MQ1HZozHCJHM56f9LmHs3HNzSKiQglPNDTP0bkV05vDYCzs3y9zA9I3yk62lRGQc0wxUY54C5ZiWnRW1kGnboAxGRgtV1tNxYHhsKVMohEC2SAOM3lXBk/Lmvfo9La+KAYOtzd9bsUzm0DFUXu2uVzMp8rHgfTa3Q+ZSk8J1OUkKza6Y=
